# ✅ Base image: Training image (does NOT include inference libs)
FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:1.13.1-cpu-py39-ubuntu20.04-sagemaker

# Set working directory
WORKDIR /opt/ml/code

# Install dependencies
RUN pip install --upgrade pip \
 && pip install pandas numpy scikit-learn boto3 s3fs cloudpickle

COPY train.py /opt/ml/code/train.py
COPY preprocess.py /opt/ml/code/preprocess.py

# Set the entry point for training
# real time debugging where log is printed directly instead of being stored somewhere, can also be used in Dockerfile-train
ENV PYTHONUNBUFFERED=TRUE
