# Use official SageMaker inference base image for CPU
FROM 763104351884.dkr.ecr.ap-south-1.amazonaws.com/sagemaker-scikit-learn:1.0-1-cpu-py3

# Set working directory
WORKDIR /opt/ml/code

# Install any extra dependencies if needed
RUN pip install --upgrade pip \
 && pip install pandas numpy s3fs

# Copy inference script
COPY serve.py /opt/ml/code/serve.py

# real time debugging where log is printed directly instead of being stored somewhere, can also be used in Dockerfile-train
ENV PYTHONUNBUFFERED=TRUE
ENV SAGEMAKER_PROGRAM=serve.py
