# Use official SageMaker inference base image for CPU
FROM 683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-scikit-learn:1.2-1-cpu-py3

# Set working directory
WORKDIR /opt/ml/code

# Install any extra dependencies if needed
RUN pip install --upgrade pip \
 && pip install \
    scikit-learn==1.5.1 \
    cython==3.0.10 \
    pandas \
    numpy \
    joblib \
    s3fs \
    cloudpickle

# Copy inference script
COPY serve.py /opt/ml/code/serve.py

# real time debugging where log is printed directly instead of being stored somewhere, can also be used in Dockerfile-train
ENV PYTHONUNBUFFERED=TRUE
ENV SAGEMAKER_PROGRAM=serve.py