# Dockerfile-inference

FROM python:3.9-slim

WORKDIR /opt/ml/code

RUN apt-get update && apt-get install -y gcc \
 && pip install --upgrade pip \
 && pip install \
    scikit-learn==1.5.1 \
    pandas \
    numpy \
    joblib \
    s3fs \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

COPY serve.py /opt/ml/code/serve.py

# Required env vars
ENV SAGEMAKER_PROGRAM=serve.py
ENV PYTHONUNBUFFERED=TRUE

# ✅ Explicitly set entrypoint to run inference script
ENTRYPOINT ["python", "serve.py"]
